#
#    ███████╗██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
#    ██╔════╝██╔══██╗██║██╔════╝██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
#    █████╗  ██████╔╝██║██║     ██║  ███╗██║   ██║███████║██████╔╝██║  ██║
#    ██╔══╝  ██╔═══╝ ██║██║     ██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
#    ███████╗██║     ██║╚██████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#    ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
# Thank you for downloading my plugin!
# SpigotMC Link: https://www.spigotmc.org/resources/epicguard-advanced-server-protection-antibot-more.72369/
# My Discord: iShift#0524

geographical:
  # You can decide which databases the plugin should download.
  # Disabling 'country database' will disable this entire check.
  download-databases:
    city: true
    country: true
  # This has three values:
  # WHITELIST = countries listed below CAN join, every other can't.
  # BLACKLIST = countries listed below CAN'T join, every other can.
  # DISABLED = disable this module.
  mode: DISABLED
  # List of country codes: https://dev.maxmind.com/geoip/legacy/codes/iso3166/
  list:
    - GB
    - DE

# Configuration of all antibot detections.
antibot:
  # If a player/bot's nickname contains one of the values below, he will be blocked.
  name-contains-check:
    - mcstorm
    - mcspam
    - proxy
    - mcdrop
  # If there are too many connetions with similiar nickname, they will be blocked.
  name-similiarity-check:
    enabled: true
    amount: 6
  # Simple proxy check, which will use proxycheck.io with your specified key.
  # Register on https://proxycheck.io/dashboard and get a free API KEY!
  # You can leave it empty, but your protection will be limited.
  # If you are using advanced-proxy-checker, this section is ignored.
  simple-proxy-check:
    enabled: true
    api-key: "YOUR_KEY"
  # Additional protection aka "Attack Mode".
  # When certain conditions are met, this mode will enable.
  # Additional checks will be performed to block every bot.
  additional-protection:
    # Time in seconds between next condition check.
    # If conditions aren't met, additional protection will be disabled.
    check-conditions-delay: 10
    # Only one condition will need to be met to activate attack mode.
    conditions:
      connections-per-second: 6
      ping-per-second: 15
      detections-per-second: 3
    # This checks will only perform when there is an active attack!
    checks:
      # Players will need to re-join the server.
      rejoin-check: true
      # Players will need to ping the server (add to server list).
      server-list-check: true

# Enabling advanced-proxy-checker will disable simple-proxy-check.
# It will use all the sites you have set below.
# Only for advanced users!
advanced-proxy-checker:
  enabled: false
  checkers:
    '1':
      url: "https://proxycheck.io/v2/{ADDRESS}"
      contains:
        - yes
        - VPN

# If console log contains text listed below, it
# will be hidden. This will decrease CPU usage.
console-filter:
  enabled: true
  messages:
    - Disconnecting
    - lost connection
    - authlib
    - GameProfile
    - InitialHandler

auto-whitelist:
  # Enable automatic player whitelisting.
  # When a player is whitelisted, all checks are skipped.
  enabled: true
  # How much time (in ticks), the player should be online to be added to the whitelist.
  # 20 ticks = 1 second
  time: 8400