#
#    ███████╗██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
#    ██╔════╝██╔══██╗██║██╔════╝██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
#    █████╗  ██████╔╝██║██║     ██║  ███╗██║   ██║███████║██████╔╝██║  ██║
#    ██╔══╝  ██╔═══╝ ██║██║     ██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
#    ███████╗██║     ██║╚██████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#    ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
# Thank you for downloading my plugin!
# SpigotMC Link: https://www.spigotmc.org/resources/epicguard-advanced-server-protection-antibot-more.72369/
# My Discord: iShift#0524

###############################
##           Countries       ##
###############################

countries:
  # This has three values:
  # WHITELIST = countries listed below CAN join, every other can't.
  # BLACKLIST = countries listed below CAN'T join, every other can.
  # DISABLED = disable this module.
  mode: DISABLED
  # List of country codes:
  # https://dev.maxmind.com/geoip/legacy/codes/iso3166/
  list:
    - GB
    - DE
    - PL

###############################
##           AntiBot         ##
###############################

antibot:
  # If a player/bot's nickname contains one of the values below, he will be blocked.
  # This SHOULD be lower-case
  name-contains:
    - mcstorm
    - mcspam
    - bot
    - proxy
  # HIGHLY RECOMMENDED: Register on https://proxycheck.io/dashboard and get a free API KEY!
  # You can leave it empty, but your protection will be limited.
  # With key - 1000 requests/24h
  # Without key - 100 requests/24h
  api-key: "YOUR_KEY"

# You can change the priority of checks, by
# changing their order in the list below, or even
# disable it fully by deleting it from the list.
# Verify (check) - Forcing player to rejoin server to play
checks:
  - Blacklist
  - Attack
  - NameContains
  - Verify
  - Proxy

###############################
##        Settings           ##
###############################

# If console log contains text listed below, it
# will be hidden. This will decrease CPU usage.
console-filter:
  enabled: true
  messages:
    - Disconnecting
    - lost connection
    - authlib
    - GameProfile

# If a player doesn't send MC|Brand packet within the time provided below (delay) after joining,
# he will be kicked. Normal clients send this packet after join, but bots don't.
# WARN: Disable this if you have issues! (eg. when using ViaVersion or ProtocolSupport).
channel-verification:
  delay: 40
  enabled: true
  punish: "kick {PLAYER} &cException occurred in your connection, please rejoin!"
# If a player sends MC|Brand packet with a value listed below, he will be kicked.
# Normal (Vanilla) clients use 'vanilla'
blocked-brands:
  enabled: true
  punish: "kick {PLAYER} &cYour client is not allowed on this server!"
  list:
    - some_blocked_brand

updater: true
###############################
##           Advanced        ##
###############################
# You SHOULD configure it, to fit your server's player amount.
# If you have small server, don't change it, or change it to smaller values

speed:
  # How many connections per second should be made, to block connections to the server.
  # Whitelisted players still can join, if CPS is below this value, connection blocking will be disabled.
  # If deny-join is triggered, Proxy/VPN checking is skipped.
  connection: 7
  # How many pings per second should be made to block connections to the server.
  ping-speed: 10
  # Time (in ticks) before the antibot will disable.
  attack-timer-reset: 800

# Block tab-complete packet using ProtocolLib.
# Useful when using a multi-version server, because 1.13+ players
# receive different packet than older version players.
fully-block-tab-complete: false

# When the server is attacked with PING method, server
# MOTD and player slots, won't be displayed to optimize bandwidth
bandwidth-optimizer: true

auto-whitelist:
  # Enable automatic player whitelisting.
  # When a player is whitelisted, all checks are skipped (like a Proxy check).
  # Whitelisted players can join even when ATTACK_MODE is activated.
  enabled: true
  # How much time (in ticks), the player should be online to be added to the whitelist.
  # 20 ticks = 1 second
  time: 8400

###############################
##     Server Protection     ##
###############################

ip-history:
  enabled: true

op-protection:
  enabled: false
  # EXPERIMENTAL: Protection from backdoor using PermissionsEx "*" permission.
  # Enable this if you are using PEX plugin and you want additional protection.
  pex-protection: false
  # Permission to see alert: epicguard.protection.notify
  alert: "&cPlayer &6{PLAYER} &chas been banned for Force-OP."
  command: "ban {PLAYER} Force-OP"
  # List of players who can have OP
  list:
    - "Admin"

# If someone tries to execute command listed here,
# event will be canceled, and the player will see a custom message
# defined in messages.yml

command-protection:
  enabled: false
  list:
    - /op
    - /stop

# If someone tries to execute a command not listed
# in this module, and does not have bypass permission,
# event will be canceled, and custom message will be shown

allowed-commands:
  enabled: false
  # If someone execute command not listed below,
  # without permission to bypass, will get custom message
  # defined in messages.yml
  list:
    - /msg
    - /home

# Replaces default tab completion in /<tab>,
# with your custom list, provided below.
# WARN: You NEED ProtocolLib!
custom-tab-complete:
  enabled: false
  list:
    - /msg
    - /home

# Toggle ability to bypass specific modules
# if player has permission for it.
bypass:
  # Permission: epicguard.bypass.allowed-commands
  allowed-commands: true
  # Permission: epicguard.bypass.custom-tab-complete
  custom-tab-complete: false
###############################
##           Firewall        ##
###############################

firewall:
  # Don't use on free / shared hosting!
  # You need private machine with IPTables (or something else) installed.
  enabled: false
  # Executed in /guard blacklist <player> OR while player was detected as a BOT
  command-blacklist: "iptables -A INPUT -s {IP} -j DROP"
  # Executed in /guard whitelist <player>
  command-whitelist: "iptables -D INPUT -s {IP} -j DROP"