#
#    ███████╗██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
#    ██╔════╝██╔══██╗██║██╔════╝██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
#    █████╗  ██████╔╝██║██║     ██║  ███╗██║   ██║███████║██████╔╝██║  ██║
#    ██╔══╝  ██╔═══╝ ██║██║     ██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
#    ███████╗██║     ██║╚██████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#    ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
#
# Thank you for downloading my plugin!
# SpigotMC Link: https://www.spigotmc.org/resources/%E2%9C%A9-epicguard-1-8-1-14-antibot-antivpn-proxy-spigot-bungeecord-staff-protection-tools-%E2%9C%A9.72369/
# My Discord: PolskiStevek#2198

###############################
##    Main Options           ##
###############################
main-permission: "epicguard.admin"
updater: true

# Yeah yeah, another "DO NOT TOUCH" option!
config-version: 1

###############################
##           Countries       ##
###############################

countries:
  # This has three values:
  # WHITELIST = countries listed below CAN join, every other can't.
  # BLACKLIST = countries listed below CAN'T join, every other can.
  # DISABLED = disable this module.
  mode: WHITELIST
  # List of country codes:
  # https://dev.maxmind.com/geoip/legacy/codes/iso3166/
  list:
    - US
    - GB
    - DE

###############################
##           AntiBot         ##
###############################

antibot:
  # You can fuly disable ALL antibot modules if you don't want it.
  # Disabling antibot will not disable country checking (look above)
  enabled: true
  # HIGHLY RECOMMENDED: Register on https://proxycheck.io/dashboard and get a free API KEY!
  # Then replace the URL "http://proxycheck.io/v2/{IP}&vpn=1" to this:
  # "http://proxycheck.io/v2/{IP}?key=API_KEY&vpn=1"
  checkers:
    '1':
      adress: "http://proxycheck.io/v2/{IP}&vpn=1"
    '2':
      adress: "http://www.stopforumspam.com/api?ip={IP}"
    '3':
      adress: "https://ip.teoh.io/{IP}"
    # What should the return message of each page contain?
    responses:
      - "yes"
      - "true"
      - "Bad"

###############################
##           Advanced        ##
###############################

speed:
  # How many connections per seconds should me made, to block connections to the server.
  # Whitelisted players still can join, if CPS is below this value, connection blocking will be disabled.
  # If deny-join is triggered, Proxy/VPN checking is skipped.
  connection: 10
  # How many pings per seconds should be made to block connections to the server.
  ping-speed: 15
  # How many successful joins per second should me made to block connections to the server
  join-speed: 5
  # Time (in ticks) before antibot will disable.
  attack-timer-reset: 800

auto-whitelist:
  # Enable automatic player whitelisting.
  # When player is whitelisted, all checks are skipped (like Proxy check).
  # Whitelisted players can join even when ATTACK_MODE is activated. Bots can't join but players can.
  enabled: true
  # How much time (in ticks), player should be online to be added to whitelist.
  # 20 ticks = 1 second
  time: 2400

###############################
##           Firewall        ##
###############################

firewall:
  # Don't use on free / shared hosting! (It wont work, but it will spam your chat on attack)
  # You need VPS / Dedicated with IPTables (or something else) installed on your machine.
  enabled: false
  # Executed in /guard blacklist <player> OR while player was detected as a BOT
  command-blacklist: "iptables -A INPUT -s {IP} -j DROP"
  # Executed in /guard whitelist <player>
  command-whitelist: "iptables -D INPUT -s {IP} -j DROP"