#
#    ███████╗██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
#    ██╔════╝██╔══██╗██║██╔════╝██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
#    █████╗  ██████╔╝██║██║     ██║  ███╗██║   ██║███████║██████╔╝██║  ██║
#    ██╔══╝  ██╔═══╝ ██║██║     ██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
#    ███████╗██║     ██║╚██████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#    ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
#
# Thank you for downloading my plugin!
# SpigotMC Link: https://www.spigotmc.org/resources/%E2%9C%A9-epicguard-1-8-1-14-antibot-antivpn-proxy-spigot-bungeecord-staff-protection-tools-%E2%9C%A9.72369/
# My Discord: PolskiStevek#2198
#
# Looks like You are using BungeeCord version.
# This is still a beta release, i suggest using it
# only on Spigot-Based servers. But antibot is functional,
# You can block vpn / proxies and countries, and attack speed.
# Firewall is also working, but there is no included whitelist and blacklist system.

###############################
##           Countries       ##
###############################

countries:
  # This has three values:
  # WHITELIST = countries listed below CAN join, every other can't.
  # BLACKLIST = countries listed below CAN'T join, every other can.
  # DISABLED = disable this module.
  mode: WHITELIST
  # List of country codes:
  # https://dev.maxmind.com/geoip/legacy/codes/iso3166/
  list:
    - PL

###############################
##           Advanced        ##
###############################

attack-speed:
  # How many connections per seconds should me made, to block connections to the server.
  # Whitelisted players still can join, if CPS is below this value, connection blocking will be disabled.
  # If deny-join is triggered, Proxy/VPN checking is skipped.
  deny-join: 3
  # How many pings per seconds should be made to block connections to the server.
  ping-speed: 10

###############################
##           Firewall        ##
###############################

firewall:
  # Don't use on free / shared hosting! (It wont work, but it will spam your chat on attack)
  # You need VPS / Dedicated with IPTables (or something else) installed on your machine.
  enabled: false
  # Executed in /guard blacklist <player> OR while player was detected as a BOT
  command-blacklist: "iptables -A INPUT -s {IP} -j DROP"
  # Executed in /guard whitelist <player>
  command-whitelist: "iptables -D INPUT -s {IP} -j DROP"

###############################
##           AntiBot         ##
###############################

antibot:
  # HIGHLY RECOMMENDED: Register on https://proxycheck.io/dashboard and get a free API KEY!
  # Then replace the URL "http://proxycheck.io/v2/{IP}&vpn=1" to this:
  # "http://proxycheck.io/v2/%ip%?key=API_KEY&vpn=1"
  checkers:
    '1':
      adress: "http://proxycheck.io/v2/{IP}&vpn=1"
    '2':
      adress: "http://www.stopforumspam.com/api?ip={IP}"
    '3':
      adress: "https://ip.teoh.io/{IP}"
    # What should any of above sites return?
    responses:
      - "yes"
      - "true"
      - "Bad"
  kick-messages:
    # Better multiline kick-messages coming in 2.0 Update.
    proxy: "&8▪ &cEpicGuard AntiBot &8▪\n\n&7Our systems have detected, that you are using Proxy or VPN.\n&7Please disable VPN programs, and join server.\n&7If you think this is an issue, contact our staff."
    blacklist: "&8▪ &cEpicGuard AntiBot &8▪\n\n&7Your IP have been blacklisted.\n&7If you think this is an issue, please contact our staff."
    attack: "&8▪ &cEpicGuard AntiBot &8▪\n\n&7Our server is being attacked.\n&7Please wait some minutes and join."
    country: "&8▪ &cEpicGuard AntiBot &8▪\n\n&7Your country is not allowed.\n&7If you think this is an issue, please contact our staff."