#
#    ███████╗██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
#    ██╔════╝██╔══██╗██║██╔════╝██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
#    █████╗  ██████╔╝██║██║     ██║  ███╗██║   ██║███████║██████╔╝██║  ██║
#    ██╔══╝  ██╔═══╝ ██║██║     ██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
#    ███████╗██║     ██║╚██████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#    ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
# Thank you for downloading my plugin!
# SpigotMC Link: https://www.spigotmc.org/resources/epicguard-advanced-server-protection-antibot-more.72369/
# My Discord: iShift#0524

###############################
##           Countries       ##
###############################

countries:
  # This has three values:
  # WHITELIST = countries listed below CAN join, every other can't.
  # BLACKLIST = countries listed below CAN'T join, every other can.
  # DISABLED = disable this module.
  mode: DISABLED
  # List of country codes:
  # https://dev.maxmind.com/geoip/legacy/codes/iso3166/
  list:
    - GB
    - DE
  download-databases:
    country: true

###############################
##           AntiBot         ##
###############################

antibot:
  # If a player/bot's nickname contains one of the values below, he will be blocked.
  # This SHOULD be lower-case
  name-contains:
    - mcstorm
    - mcspam
    - bot
    - proxy
  # HIGHLY RECOMMENDED: Register on https://proxycheck.io/dashboard and get a free API KEY!
  # You can leave it empty, but your protection will be limited.
  # With key - 1000 requests/24h
  # Without key - 100 requests/24h
  api-key: "YOUR_KEY"
  # This two checks will only perform when there is an active attack!
  rejoin-check: true
  server-list-check: true

# If console log contains text listed below, it
# will be hidden. This will decrease CPU usage.
console-filter:
  enabled: true
  messages:
    - Disconnecting
    - lost connection
    - authlib
    - GameProfile

###############################
##           Advanced        ##
###############################
# You SHOULD configure it, to fit your server's player amount.
# If you have small server, don't change it, or change it to smaller values

speed:
  # How many connections per second should be made to activate additional checks.
  connection: 5
  # How many pings per second should be made to activate additional checks.
  ping-speed: 7

###############################
##           Firewall        ##
###############################

firewall:
  # Don't use on free / shared hosting!
  # You need private machine with IPTables (or something else) installed.
  enabled: false
  # Executed in /guard blacklist <player> OR while player was detected as a BOT
  command-blacklist: "iptables -A INPUT -s {IP} -j DROP"
  # Executed in /guard whitelist <player>
  command-whitelist: "iptables -D INPUT -s {IP} -j DROP"