name: '${project.name}'
version: '${project.version}'
main: io.github.polskistevek.epicguard.bukkit.GuardPluginBukkit
softdepend: [ProtocolLib]
author: PolskiStevek
description: Increase your server security. Fast and effective. Block bots, griefers. Block any ForceOP.
api-version: 1.14

commands:
  epicguard:
    description: Main plugin command.
    aliases: [ab, guard, eg]