name: '${project.name}'
version: '${project.version}'
main: me.ishift.epicguard.bukkit.GuardBukkit
softdepend: [ProtocolLib]
author: PolskiStevek
description: Increase your server security. Fast and effective. Block bots, griefers. Block any ForceOP.
api-version: 1.13

commands:
  epicguard:
    description: Main plugin command.
    aliases: [ab, guard, eg]