name: EpicGuard
version: 1.2
main: pl.polskistevek.guard.bukkit.BukkitMain
softdepend: [ProtocolLib]
author: PolskiStevek
description: Lightweight antibot for your server!

commands:
  core:
    aliases: [ab, guard, eg, epicguard]