#
#    ███████╗██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ██████╗
#    ██╔════╝██╔══██╗██║██╔════╝██╔════╝ ██║   ██║██╔══██╗██╔══██╗██╔══██╗
#    █████╗  ██████╔╝██║██║     ██║  ███╗██║   ██║███████║██████╔╝██║  ██║
#    ██╔══╝  ██╔═══╝ ██║██║     ██║   ██║██║   ██║██╔══██║██╔══██╗██║  ██║
#    ███████╗██║     ██║╚██████╗╚██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝
#    ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝
# Created by RushMC Team (iShift & ruzekh).
# Important plugin section.
name: EpicGuard
version: '${project.version}'
main: me.ishift.epicguard.bukkit.GuardBukkit
load: STARTUP
softdepend: [ProtocolLib, EssentialsGeoIP]

# Other information about plugin section.
authors: [iShift, ruzekh]
website: https://www.spigotmc.org/resources/72369/
description: Spigot & Bungee - Advanced server protection package!
api-version: '1.13'

# Plugin commands section.
commands:
  epicguard:
    description: Main plugin command.
    aliases: [ab, guard, eg, antibot]