name: '${project.name}'
version: '${project.version}'
main: me.ishift.epicguard.bukkit.GuardBukkit
softdepend: [ProtocolLib]
authors: [iShift, ruzekh]
description: Advanced Server Protection.
api-version: 1.13

commands:
  epicguard:
    description: Main plugin command.
    aliases: [ab, guard, eg]