name: EpicGuard
version: 2.1.0
main: pl.polskistevek.guard.bukkit.GuardPluginBukkit
softdepend: [ProtocolLib]
author: PolskiStevek
description: Increase your server security. Fast and effective, Block bots, griefers, Bungeecord Supported!
api-version: 1.14

commands:
  core:
    aliases: [ab, guard, eg, epicguard]