name: EpicGuard
version: 2.2.0
main: pl.polskistevek.guard.bukkit.BukkitMain
softdepend: [ProtocolLib]
author: PolskiStevek
description: Increase your server security. Fast and effective, Block bots, griefers, Bungeecord Supported!
api-version: 1.15

commands:
  core:
    aliases: [ab, guard, eg, epicguard]