name: EpicGuard
version: '${project.version}'
main: me.ishift.epicguard.bukkit.PlatformBukkit

author: iShift
website: https://www.spigotmc.org/resources/72369/

commands:
  epicguard:
    description: Main plugin command.
    aliases: [ab, guard, eg, antibot]