name: EpicGuard
version: '${project.version}'
main: me.xneox.epicguard.bukkit.PlatformBukkit

author: xNeox
website: https://www.spigotmc.org/resources/72369/
description: Simple but effective bot protection system.

commands:
  epicguard:
    description: Main plugin command.
    aliases: [ab, guard, eg, antibot]