#   ▄███████▄    ▄█    █▄     ▄██████▄     ▄████████ ███▄▄▄▄    ▄█  ▀████    ▐████▀
#   ███    ███   ███    ███   ███    ███   ███    ███ ███▀▀▀██▄ ███    ███▌   ████▀
#   ███    ███   ███    ███   ███    ███   ███    █▀  ███   ███ ███▌    ███  ▐███
#   ███    ███  ▄███▄▄▄▄███▄▄ ███    ███  ▄███▄▄▄     ███   ███ ███▌    ▀███▄███▀
# ▀█████████▀  ▀▀███▀▀▀▀███▀  ███    ███ ▀▀███▀▀▀     ███   ███ ███▌    ████▀██▄
#   ███          ███    ███   ███    ███   ███    █▄  ███   ███ ███    ▐███  ▀███
#   ███          ███    ███   ███    ███   ███    ███ ███   ███ ███   ▄███     ███▄
#  ▄████▀        ███    █▀     ▀██████▀    ██████████  ▀█   █▀  █▀   ████       ███▄
# Created by The Phoenix Team.
name: PhoenixCommons
version: '${project.version}'
main: me.ishift.commons.PhoenixCommons